---
title: "Autem Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: cosmo
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
```

```{r load, include=FALSE}
 
# Load data
step_detail_rdf <- reactive({ read_rds("data\\step_detail.RDS") })
epoch_detail_rdf <- reactive({ read_rds("data\\epoch_detail.RDS") })
simulation_summary_rdf <- reactive({ read_rds("data\\simulation_summary.RDS") })
dataset_summary_rdf <- reactive({ read_rds("data\\dataset_summary.RDS") })
baseline_detail_rdf <- reactive({ read_rds("data\\baseline_detail.RDS") })
baseline_summary_rdf <- reactive({ read_rds("data\\baseline_summary.RDS") })
breakdown_rdf <- reactive({ read_rds("data\\breakdown.RDS") })

all_value = "__all__"

experiment_rlist <- reactive({ sort(unique(simulation_summary_rdf()$experiment)) })
breakdown_rlist <- reactive({ breakdown_rdf()$breakdown })

filtered_data <- function(.data, .experiment) {
  if (.experiment == all_value)
    .data
  else
    filter(.data, experiment == .experiment)
}

# Formatters
minutes_format <- scales::unit_format(unit = "min", accuracy = 3)
accuracy_format <- scales::number_format(accuracy = .01)

```

Sidebar {.sidebar}
=====================================

```{r}

renderUI({
  tagList(
    selectInput("experiment", "Experiment:", experiment_rlist()),
    selectInput("breakdown", "Breakdown 1:", breakdown_rlist()),
    selectInput("breakdown2", "Breakdown 2:", breakdown_rlist())
  )
})

```

Overview {data-orientation=columns}
=====================================  

Overview
-----------------------------------------------------------------------

### All

```{r}

DT::renderDataTable({
  
  req(simulation_summary_rdf(), cancelOutput = TRUE)
  
  simulation_summary_df <- simulation_summary_rdf()
  
  output_df <- 
    simulation_summary_df %>%
    mutate(
      rating = readr::parse_number(format(rating, digits = 3)),
      progress_top_score = readr::parse_number(format(progress_top_score, digits = 3)),
      progress = readr::parse_number(format(progress, digits = 3))
    ) %>%
    select(
      Experiment = experiment,
      Study = study,
      Status = status,
      Steps = steps,
      `Duration (s)` = duration,
      Rating = rating,
      `Target Rating` = progress_top_score,
      Progress = progress
    )
  
  DT::datatable(output_df)
  
})

```

Summary {data-orientation=columns}
=====================================  

### Status

```{r}

DT::renderDataTable({
  req(simulation_summary_rdf(), input$experiment, cancelOutput = TRUE)
  
  simulation_summary_df <- simulation_summary_rdf() %>% filtered_data(input$experiment)
  
  output_df <- 
    simulation_summary_df %>%
    mutate(
      rating = readr::parse_number(format(rating, digits = 3)),
      progress_top_score = readr::parse_number(format(progress_top_score, digits = 3)),
      progress = readr::parse_number(format(progress, digits = 3))
    ) %>%
    select(
      Experiment = experiment,
      Study = study,
      Status = status,
      Steps = steps,
      `Duration (s)` = duration,
      Rating = rating,
      `Target Rating` = progress_top_score,
      Progress = progress
    )
  
  DT::datatable(output_df, options = list(bPaginate = FALSE, bFilter = FALSE))

})

```

### Data

```{r}

DT::renderDataTable({
  req(dataset_summary_rdf(), input$experiment, cancelOutput = TRUE)
  
  experiment = input$experiment
  
  dataset_summary_df <- dataset_summary_rdf() %>% filter(dataset == experiment)
  output_df <- 
    dataset_summary_df %>%
    select(
      Dataset = dataset,
      Classes = classes,
      Features = features,
      Instances = instances,
      Incomplete = incomplete,
      Missing = missing
    )
  
  DT::datatable(output_df, options = list(bPaginate = FALSE, bFilter = FALSE))

})

```

"study"                 "experiment"            "dataset"               "status"                "classes"               "features"              "instances"            
 [8] "incomplete_instances"  "missing_values"        "duration"              "epochs"                "steps"                 "score"                 "score_sd"             
[15] "dummy_score"           "validation_score"      "baseline_bottom_score" "baseline_top_score"    "progress_bottom_score" "progress_top_score"    "progress"             
[22] "progress_sd"

Baselines {data-orientation=columns}
=====================================  

Left
-----------------------------------------------------------------------

### All progress

```{r}

renderPlot({
  req(simulation_summary_rdf(), cancelOutput = TRUE)

  df <- simulation_summary_rdf() %>% 
    filter(!is.na(progress)) %>%
    mutate(experiment = forcats::fct_reorder(experiment, desc(progress))) %>%
    select(experiment, study, progress, progress_std)

  p <- df %>%
    ggplot(aes(x = experiment, color = study)) +
    geom_errorbar(aes(ymin = progress-progress_std, ymax=progress+progress_std), width = 0.5, na.rm = TRUE) +
    geom_point(aes(y = progress)) +
    geom_hline(aes(yintercept = 1.0), linetype = 'dotted') +
    geom_hline(aes(yintercept = 0.95), linetype = 'dotted') +
    ylab("Progress") +
    coord_flip(ylim = c(0.4, 1.1))


  p

})

```

Right
-----------------------------------------------------------------------

### Progress Density

```{r}

renderPlot({
  req(simulation_summary_rdf(), cancelOutput = TRUE)
  
  df <- simulation_summary_rdf() %>% filter(!is.na(progress))
  p <- df %>%
    ggplot(aes(x = progress, color = study)) +
    geom_density() +
    xlab("Progress") +
    ylab("Density")
  p

})

```

### Experiment Progress

```{r}

renderPlot({
  req(simulation_summary_rdf(), baseline_detail_rdf(), input$experiment, cancelOutput = TRUE)
  
  experiment = input$experiment
  
  simulation_summary_df <- simulation_summary_rdf() %>% filtered_data(experiment)
  simulation_summary_df <-
    simulation_summary_df %>%
    mutate(validation_progress = (validation_score - progress_bottom_score) / (progress_top_score - progress_bottom_score))
  
  baseline_detail_df <- baseline_detail_rdf() %>% filter(dataset == simulation_summary_df$dataset)
  
  baseline_progress_df <-
    simulation_summary_df %>%
    right_join(baseline_detail_df, by = c("dataset")) %>%
    mutate(
      baseline_progress = (baseline_score - progress_bottom_score) / (progress_top_score - progress_bottom_score)
    ) %>%
    select(study, experiment, baseline_score, baseline_rank, baseline_percent, baseline_progress) %>%
    filter(baseline_progress >= 0)
  
  simulation_summary_progress <-
    simulation_summary_df %>%
    full_join(baseline_progress_df, by = c("study", "experiment")) %>%
    filter(baseline_score <= rating) %>%
    group_by(study, experiment) %>%
    summarise(baseline_rank = max(baseline_rank), baseline_percent = max(baseline_percent))
  
  simulation_summary_df <- 
    simulation_summary_df %>%
    full_join(simulation_summary_progress, by = c("study", "experiment"))
  
  baseline_progress_df %>%
      ggplot() +
      geom_count(aes(x = baseline_percent, y = baseline_progress), color = "DarkGrey") +
      geom_point(data = simulation_summary_df, aes(x = baseline_percent, y = progress, color = study, shape ="score"), size = 3) +
      geom_rug(data = simulation_summary_df, aes(x = baseline_percent, y = progress, color = study), sides="trbl") +
      geom_errorbar(data = simulation_summary_df, aes(x = baseline_percent, ymin = progress-progress_std, ymax=progress+progress_std), width = 0.05, na.rm = TRUE) +
      geom_point(data = simulation_summary_df, aes(x = baseline_percent, y = validation_progress, color = study, shape ="validation"), size = 3) +
      geom_hline(aes(yintercept = 1.0), linetype = 'dotted') +
      geom_hline(aes(yintercept = 0.0), linetype = 'dotted') +
      xlim(0.0, 1.0) +
      xlab("Baseline rank") +
      ylab("Progress")
})

```

Validation {data-orientation=columns}
=====================================  

Left
-----------------------------------------------------------------------

### All Details

```{r}

renderPlot({
  req(simulation_summary_rdf(), cancelOutput = TRUE)

  simulation_summary_df <- simulation_summary_rdf() %>% filter(!is.na(validation_score))

  output_df <-
    simulation_summary_df %>%
    mutate(
      validation_distance = (validation_score - score) / score_std
    ) %>%
    filter(!is.na(validation_distance)) %>%
    mutate(
      experiment = forcats::fct_reorder(experiment, abs(validation_distance))
    ) %>%
    select(
      study,
      experiment,
      dataset,
      rating,
      rating_std,
      validation_score,
      validation_distance
    )

  output_df %>%
    ggplot(aes(x = experiment, color = study)) +
    geom_point(aes(y = validation_distance)) +
    geom_hline(aes(yintercept = 0), linetype = 'solid') +
    geom_hline(aes(yintercept = -1), linetype = 'dotdash') +
    geom_hline(aes(yintercept = 1), linetype = 'dotdash') +
    geom_hline(aes(yintercept = -2), linetype = 'dotted') +
    geom_hline(aes(yintercept = 2), linetype = 'dotted') +
    coord_flip()
  
})

```

Compact
-----------------------------------------------------------------------

### Validation Density

```{r}
renderPlot({
  req(simulation_summary_rdf(), cancelOutput = TRUE)

  simulation_summary_df <- simulation_summary_rdf() %>% filter(!is.na(validation_score))

  output_df <-
    simulation_summary_df %>%
    mutate(
      validation_distance = (validation_score - score) / score_std
    ) %>%
    filter(!is.na(validation_distance)) %>%
    mutate(
      experiment = forcats::fct_reorder(experiment, desc(abs(validation_distance)))
    ) %>%
    select(
      study,
      experiment,
      dataset,
      rating,
      rating_std,
      validation_score,
      validation_distance
    )

  output_df %>%
    ggplot(aes(x = validation_distance, color = study)) +
    geom_density()
})

```

### Selected Validation

```{r}

renderPlot({
  req(simulation_summary_rdf(), input$experiment, cancelOutput = TRUE)

  experiment <- input$experiment
  simulation_summary_df <- simulation_summary_rdf() %>% filtered_data(experiment)

  output_df <-
    simulation_summary_df %>%
    select(
      study,
      experiment,
      dataset,
      rating,
      rating_std,
      validation_score
    )
  
  output_df %>%
    ggplot(aes(x = study)) +
    geom_errorbar(aes(ymin = rating-rating_std, ymax=rating+rating_std), width = .3, color = "black") +
    geom_errorbar(aes(ymin = rating-rating_std * 2, ymax=rating+rating_std* 2), width = .15, color = "black", linetype = 'dotted') +
    geom_point(aes(y = rating, color = "score"), size = 3) +
    geom_point(aes(y = validation_score, color = "validation"), size = 3) +
    coord_flip() +
    xlab("Study") +
    ylab("Score")

})
```

Scores {data-orientation=rows}
=====================================

Top
-----------------------------------------------------------------------

### Learning Curve

```{r}

renderPlot({
  req(step_detail_rdf(), simulation_summary_rdf(), input$experiment, input$breakdown, cancelOutput = TRUE)
  
  step_detail_df <- 
    step_detail_rdf() %>% 
    filtered_data(input$experiment) %>%
    filter(!is.na(score), !is.na(validation_score)) %>%
    group_by(member_id, league) %>%
    filter(step == min(step)) %>%
    ungroup()
  
  # define the model
  score_model <- loess(score ~ step, data = step_detail_df)
  validation_model <- loess(validation_score ~ step, data = step_detail_df)
  step_detail_df$score_smooth <- predict(score_model)
  step_detail_df$validation_score_smooth <- predict(validation_model)

  simulation_summary_df <- simulation_summary_rdf() %>% filtered_data(input$experiment)
  
  req(nrow(step_detail_df) > 0, cancelOutput = TRUE)  

  step_detail_df %>%
    ggplot() +
    geom_ribbon(aes(x = step, ymin=score_smooth-score_std, ymax=score_smooth+score_std), fill = "LightGrey", na.rm = TRUE) +
    geom_line(aes(x = step, y = score_smooth, linetype = "Training"), na.rm = TRUE) +
    geom_smooth(aes(x = step, y = validation_score_smooth, linetype = "Validation"), na.rm = TRUE, method = "loess", se = FALSE) +
    geom_point(aes(x = step, y = score, color = !!as.symbol(input$breakdown), shape = "Training"), na.rm = TRUE) +
    geom_point(aes(x = step, y = validation_score, color = !!as.symbol(input$breakdown), shape = "Validation"), na.rm = TRUE) +
    geom_hline(data = simulation_summary_df, aes(yintercept = baseline_top_score), linetype = 'dotted') +
    geom_label(data = simulation_summary_df, aes(x = 0, y = baseline_top_score, label = accuracy_format(baseline_top_score))) +
    geom_hline(data = simulation_summary_df, aes(yintercept = baseline_bottom_score), linetype = 'dotted') +
    geom_label(data = simulation_summary_df, aes(x = 0, y = baseline_bottom_score, label = accuracy_format(baseline_bottom_score))) +
    facet_wrap(~ study) +
    coord_cartesian(ylim = c(0, 1))
})

```

Bottom
-----------------------------------------------------------------------

### Predictions

```{r}

renderPlot({
  req(step_detail_rdf(), simulation_summary_rdf(), input$experiment, input$breakdown, cancelOutput = TRUE)
  
  step_detail_df <- 
    step_detail_rdf() %>% 
    filtered_data(input$experiment) %>%
    filter(!is.na(score), !is.na(choice_score)) %>%
    group_by(member_id, league) %>%
    filter(step == min(step)) %>%
    mutate(
      predicted_score = choice_score,
      predicted_score_std = choice_score_std
    ) %>%
    ungroup()
  simulation_summary_df <- simulation_summary_rdf() %>% filtered_data(input$experiment)
  
  req(nrow(step_detail_df) > 0, cancelOutput = TRUE)  
  
  step_detail_df %>%
    ggplot(aes(x = step)) +
    geom_point(aes(y = predicted_score), size = 3, shape=1, color = "Grey", na.rm = TRUE) +
    geom_point(aes(y = score, color = !!as.symbol(input$breakdown)), size = 1, na.rm = TRUE) +

    geom_hline(data = simulation_summary_df, aes(yintercept = baseline_top_score), linetype = 'dotted') +
    geom_label(data = simulation_summary_df, aes(x = 0, y = baseline_top_score, label = accuracy_format(baseline_top_score))) +
    geom_hline(data = simulation_summary_df, aes(yintercept = baseline_bottom_score), linetype = 'dotted') +
    geom_label(data = simulation_summary_df, aes(x = 0, y = baseline_bottom_score, label = accuracy_format(baseline_bottom_score))) +
    facet_wrap(~ study) +
    coord_cartesian(ylim = c(0, 1))
})

```


Scores 2 {data-orientation=rows}
=====================================

Top
-----------------------------------------------------------------------

### Counts

```{r}

renderPlot({
  req(breakdown_rlist(), step_detail_rdf(), input$experiment, cancelOutput = TRUE)
  
  step_detail_df <- step_detail_rdf() %>% filtered_data(input$experiment) %>% filter(final == 1)
  choices_list <- breakdown_rlist()
  
  req(nrow(step_detail_df) > 0, cancelOutput = TRUE)
  
  build_component_summary <- function(.choice) { 
    step_detail_df %>% 
      group_by_at(c("study", "experiment", .choice)) %>% 
      summarise(n = n()) %>%
      mutate(choice = .choice) %>%
      select(study, experiment, choice, component = !! .choice, n)
  }
  
  choices_summary_df <-  
    purrr::map_dfr(choices_list,  build_component_summary) %>%
    mutate(choice = factor(choice))
  
  choices_summary_df %>%
    ggplot() +
    geom_col(aes(x = forcats::fct_reorder(component, choice, .fun = unique, .desc = TRUE), y = n, fill = choice)) + 
    coord_flip() +
    xlab("Component") +
    facet_wrap(~ study)
})
```

### Scores 

```{r}

renderPlot({
  req(breakdown_rlist(), step_detail_rdf(), input$experiment, cancelOutput = TRUE)
  
  step_detail_df <- step_detail_rdf() %>% filtered_data(input$experiment) %>% filter(final == 1)
  choices_list <- breakdown_rlist()
  
  req(nrow(step_detail_df) > 0, cancelOutput = TRUE)
  
  build_choice_scores <- function(choice) { 
    step_detail_df %>% 
      mutate(
        choice = choice,
        predicted_score = choice_score
      ) %>%
      select(study, experiment, choice, component = !! choice, score, predicted_score)
  }
  
  choices_score_df <-  
    purrr::map_dfr(choices_list,  build_choice_scores) %>%
    mutate(
      choice = factor(choice),
      component = forcats::fct_reorder(component, choice, .fun = unique, .desc = TRUE)
    )

  choices_score_df %>%
    ggplot() +
    geom_point(aes(x = component, y = predicted_score), size = 3, shape=1, color = "Grey", na.rm = TRUE) +
    geom_point(aes(x = component, y = score, color = choice), size = 1, na.rm = TRUE) +
    coord_flip() +
    xlab("Component") +
    facet_wrap(~ study)

})

```

Bottom
-----------------------------------------------------------------------

### Placeholder 1

### Placeholder 2 

Durations {data-orientation=rows}
=====================================

Top
-----------------------------------------------------------------------

### Duration

```{r}

renderPlot({
  req(step_detail_rdf(), simulation_summary_rdf(), input$experiment, input$breakdown, cancelOutput = TRUE)
  
  step_detail_df <- 
    step_detail_rdf() %>% 
    filtered_data(input$experiment) %>% 
    filter(!is.na(duration))
  simulation_summary_df <- simulation_summary_rdf() %>% filtered_data(input$experiment)
  
  req(nrow(step_detail_df) > 0, cancelOutput = TRUE)    
  
  step_detail_df %>%
    ggplot(aes(x = step, y = duration)) +
    geom_point(size = 0.5, aes(color = !!as.symbol(input$breakdown))) +
    facet_wrap(~ study)
})

```

Bottom
-----------------------------------------------------------------------

### Relative Duration

```{r}

renderPlot({
  req(step_detail_rdf(), simulation_summary_rdf(), input$experiment, input$breakdown, cancelOutput = TRUE)
  
  step_detail_df <- 
    step_detail_rdf() %>% 
    filtered_data(input$experiment) %>% 
    filter(!is.na(duration))
  simulation_summary_df <- simulation_summary_rdf() %>% filtered_data(input$experiment)
  
  req(nrow(step_detail_df) > 0, cancelOutput = TRUE)    
  
  step_detail_df %>%
    ggplot(aes(x = step, y = relative_duration)) +
    geom_point(size = 0.5, aes(color = !!as.symbol(input$breakdown))) +
    facet_wrap(~ study)
})

```

Duration 2 {data-orientation=rows}
=====================================

Top
-----------------------------------------------------------------------

### Duration

```{r}
renderPlot({
  req(breakdown_rlist(), step_detail_rdf(), input$experiment, cancelOutput = TRUE)
  
  step_detail_df <- step_detail_rdf() %>% filtered_data(input$experiment) %>% filter(!is.na(duration))
  choices_list <- breakdown_rlist()
  
  req(nrow(step_detail_df) > 0, cancelOutput = TRUE)
  
  build_choice_durations <- function(.choice) { 
    step_detail_df %>% 
      mutate(
        choice = .choice
      ) %>%
      select(study, experiment, choice, component = !! .choice, duration)
  }
  
  durations_score_df <-  
    purrr::map_dfr(choices_list,  build_choice_durations) %>%
    mutate(
      choice = factor(choice),
      component = forcats::fct_reorder(component, choice, .fun = unique, .desc = TRUE)
  )
  
  durations_score_df %>%
    ggplot() +
    geom_point(aes(x = component, y = duration, color = choice)) + 
    coord_flip() +
    xlab("Component") +
    facet_wrap(~ study)

})

```

### Standard Duration

```{r}
renderPlot({
  req(breakdown_rlist(), step_detail_rdf(), input$experiment, cancelOutput = TRUE)
  
  step_detail_df <- step_detail_rdf() %>% filtered_data(input$experiment) %>% filter(!is.na(duration))
  choices_list <- breakdown_rlist()
  
  req(nrow(step_detail_df) > 0, cancelOutput = TRUE)
  
  build_choice_durations <- function(.choice) { 
    step_detail_df %>% 
      mutate(
        choice = .choice
      ) %>%
      select(study, experiment, choice, component = !! .choice, standard_duration)
  }
  
  durations_score_df <-  
    purrr::map_dfr(choices_list,  build_choice_durations) %>%
    mutate(
      choice = factor(choice),
      component = forcats::fct_reorder(component, choice, .fun = unique, .desc = TRUE)
  )
  
  durations_score_df %>%
    ggplot() +
    geom_point(aes(x = component, y = standard_duration, color = choice)) + 
    coord_flip() +
    xlab("Component") +
    facet_wrap(~ study)

})

```


Components X {data-orientation=rows}
=====================================

Bottom
-----------------------------------------------------------------------

### Score grid

```{r}

renderPlot({
  req(breakdown_rlist(), step_detail_rdf(), input$experiment, input$breakdown, input$breakdown2, cancelOutput = TRUE)
  
  .choice1 <- input$breakdown
  .choice2 <- input$breakdown2

  step_detail_df <- step_detail_rdf() %>% filtered_data(input$experiment) %>% filter(final == 1)
  req(nrow(step_detail_df) > 0, cancelOutput = TRUE)

  choice2_detail_df <-
    step_detail_df %>% 
    mutate(
      component1 = !! sym(.choice1),
      component2 = !! sym(.choice2),
      predicted_score = choice_score,
      predicted_score_std = choice_score_std
    ) %>%
    select(study, experiment, component1, component2, score, score_std, predicted_score, predicted_score_std)

  choice2_detail_df %>%
    ggplot() +
    geom_point(aes(x = component2, y = predicted_score), size = 3, shape=1, color = "Grey", na.rm = TRUE) +
    geom_point(aes(x = component2, y = score), size = 1, na.rm = TRUE) +
    facet_wrap(component1 ~ study) +
    coord_flip()

})

```


