---
title: "Baseline Developement"
output: html_notebook
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(memoise)

reactive <- function(.x) {
  x <- function() .x
  memoise(x)
}

```

# Load data

```{r load, include=FALSE}


# Load data
step_detail_rdf <- reactive({ read_rds("data\\step_detail.RDS") })
epoch_detail_rdf <- reactive({ read_rds("data\\epoch_detail.RDS") })
simulation_summary_rdf <- reactive({ read_rds("data\\simulation_summary.RDS") })
baseline_detail_rdf <- reactive({ read_rds("data\\baseline_detail.RDS") })
baseline_summary_rdf <- reactive({ read_rds("data\\baseline_summary.RDS") })
breakdown_rdf <- reactive({ read_rds("data\\breakdown.RDS") })

all_value = "__all__"

experiment_rlist <- reactive({ sort(unique(simulation_summary_rdf()$experiment)) })
breakdown_rlist <- reactive({ breakdown_rdf()$breakdown })

filtered_data <- function(.data, .experiment) {
  if (.experiment == all_value)
    .data
  else
    filter(.data, experiment == .experiment)
}

# Formatters
minutes_format <- scales::unit_format(unit = "min", accuracy = 3)
accuracy_format <- scales::number_format(accuracy = .01)

```

Baselines
=====================================  

### All progress

```{r}

  df <- simulation_summary_rdf() %>% filter(!is.na(progress))
  min_y <- 0
  max_y <- max(df$progress + df$progress_sd)
  max_y <- if (max_y < 1) 1 else max_y

  df %>%
    mutate(experiment = forcats::fct_reorder(experiment, desc(progress))) %>%
    ggplot(aes(x = experiment, color = study)) +
    geom_point(aes(y = progress)) +
    ylim(min_y, max_y) +
    ylab("Progress") +
    coord_flip()

```

### Progress Density

```{r}

  df <- simulation_summary_rdf() %>% filter(!is.na(progress))
  min_x <- 0
  max_x <- max(df$progress + df$progress_sd)
  max_x <- if (max_x < 1) 1 else max_x
  df %>%
    ggplot(aes(x = progress, color = study)) +
    geom_density() +
    xlim(min_x, max_x) +
    xlab("Progress") +
    ylab("Density")


```

```{r}



```

  
  


  
    
  

```

```