---
title: "Keep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Normalised
-----------------------------------------------------------------------

### Selected

```{r}

renderPlot({
  req(normal_baseline_df(), simulation_summary_df(), input$dataset, cancelOutput = TRUE)
  
  summary_df <- simulation_summary_df() %>% filtered_data(input$dataset)
  min_x <- 0
  max_x <- max(summary_df$normal_rating + summary_df$normal_rating_sd)
  max_x <- if (max_x < 1) 1 else max_x

  baseline_df <- normal_baseline_df() %>% filtered_data(input$dataset)
  rating <- summary_df$rating
  summary_df$baseline_percent <- baseline_df %>% filter(baseline_accuracy <= rating) %>% pull(baseline_percent) %>% max()
  summary_df$normal_baseline_accuracy <- summary_df$normal_rating

  baseline_df %>%
    ggplot(aes(x = baseline_percent, y = normal_baseline_accuracy)) +
    geom_count(color = "DarkGrey") +
    geom_point(data = summary_df, aes(color = "rating"), size = 3) +
    geom_rug(data = summary_df, aes(color = "rating"), sides="trbl") +
    geom_errorbar(data = summary_df, aes(ymin = normal_rating-normal_rating_sd, ymax=normal_rating+normal_rating_sd), width = 0.05, na.rm = TRUE) +
    geom_point(data = summary_df, aes(y = normal_validation_accuracy, color ="validation"), size = 3) +
    geom_hline(data = summary_df, aes(yintercept = normal_max_baseline_accuracy), linetype = 'dotted') +
    geom_hline(data = summary_df, aes(yintercept = normal_dummy_accuracy), linetype = 'dotted') +
    ylim(min_x, max_x) +
    ylab("Normalised Rating")
})

```


Processing
===================================== 

Values
-----------------------------------------------------------------------

### Status

```{r}

renderValueBox({
  req(simulation_summary_df(),input$dataset, cancelOutput = TRUE)
  status <- simulation_summary_df() %>%
    filter(dataset == input$dataset) %>%
    pull(status)
  if (length(status) == 0)
    status <- NULL
  valueBox(status)
})

```

### Runtime

```{r}

renderValueBox({
  req(simulation_summary_df(),input$dataset, cancelOutput = TRUE)
  runtime_secs <- simulation_summary_df() %>% 
    filter(dataset == input$dataset) %>% 
    pull(run_time_secs)
  valueBox(minutes(runtime_secs / 60))
})

```


Epochs
-----------------------------------------------------------------------

### Events

```{r}

renderPlot({
  req(epoch_summary_df(),input$dataset, cancelOutput = TRUE)
  epoch_summary_df() %>% 
    filter(dataset == input$dataset) %>%
    ggplot(aes(x = epoch)) +
    geom_line(aes(y = faults, color = "faults")) +
    geom_line(aes(y = nominations, color = "nominations")) +
    geom_line(aes(y = deaths, color = "deaths")) +
    ylab("Epoch") +
    ylab("Count")
})

```


Steps
-----------------------------------------------------------------------

### Accuracy

```{r}

renderPlot({
  req(step_detail_df(),input$dataset, cancelOutput = TRUE)
  step_detail_df() %>% 
    filter(dataset == input$dataset, !is.na(accuracy)) %>%
    ggplot(aes(x = step, y = accuracy)) +
    geom_point(size = 0.5)
})

```

### Duration

```{r}

renderPlot({
  req(step_detail_df(),input$dataset, cancelOutput = TRUE)
  step_detail_df() %>% 
    filter(dataset == input$dataset, !is.na(accuracy)) %>%
    ggplot(aes(x = step, y = duration)) +
    geom_point(size = 0.5)
})

```

