---
title: "Status Development"
output: html_notebook
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(memoise)

reactive <- function(.x) {
  x <- function() .x
  memoise(x)
}

```

# Load data

```{r load, include=FALSE}

# Load data
step_detail_rdf <- reactive({ read_rds("data\\step_detail.RDS") })
epoch_detail_rdf <- reactive({ read_rds("data\\epoch_detail.RDS") })
simulation_summary_rdf <- reactive({ read_rds("data\\simulation_summary.RDS") })
dataset_summary_rdf <- reactive({ read_rds("data\\dataset_summary.RDS") })
baseline_detail_rdf <- reactive({ read_rds("data\\baseline_detail.RDS") })
baseline_summary_rdf <- reactive({ read_rds("data\\baseline_summary.RDS") })
breakdown_rdf <- reactive({ read_rds("data\\breakdown.RDS") })

all_value = "__all__"

experiment_rlist <- reactive({ sort(unique(simulation_summary_rdf()$experiment)) })
breakdown_rlist <- reactive({ breakdown_rdf()$breakdown })

filtered_data <- function(.data, .experiment) {
  if (.experiment == all_value)
    .data
  else
    filter(.data, experiment == .experiment)
}

# Formatters
minutes_format <- scales::unit_format(unit = "min", accuracy = 3)
accuracy_format <- scales::number_format(accuracy = .01)

```

# Print Summary

```{r}

simulation_summary_df <- simulation_summary_rdf()

output_df <- 
  simulation_summary_df %>%
  mutate(
    score = readr::parse_number(format(score, digits = 3)),
    progress_top_score = readr::parse_number(format(progress_top_score, digits = 3)),
    progress = readr::parse_number(format(progress, digits = 3))
  ) %>%
  select(
    Experiment = experiment,
    Study = study,
    Status = status,
    Steps = steps,
    `Duration (s)` = duration,
    Score = score,
    `Target Score` = progress_top_score,
    Progress = progress
  )

DT::datatable(output_df)


```

# Data Set Summary

```{r}

dataset_summary_df <- dataset_summary_rdf()
output_df <- 
  dataset_summary_df %>%
  select(
    Dataset = dataset,
    Classes = classes,
    Features = features,
    Instances = instances,
    Incomplete = incomplete,
    Missing = missing
  )

DT::datatable(output_df)

```